export const compromisoTemplateLiteral = `COMPROMISO 

TEXTO PLATAFORMA DIGITAL 'ACEPTO´´

POR MEDIO DE ESTA ACTA ACEPTO Y ME COMPROMETO A CUMPLIR LAS CONDICIONES DE ACCESO Y USO A LOS ESCENARIOS DEPORTIVOS DEL INSTITUTO DE LA JUVENTUD, EL DEPORTE Y LA RECRACION DE BUCARAMANGA.

 EL INDERBU PROHIBE:

•Ingresar alimentos y bebidas alcohólicas.
•Ingresar y manipular pólvora.
•Ingresar mascotas
 • Ingresar sustancias químicas combustibles tales como gasolina, ACPM, entre otras.
 • El ingreso de armas blancas, de fuego o traumáticas u otros objetos que lesionen la vida e integridad de las personas que usan los escenarios deportivos. 
• Extraer los equipos e implementos deportivos sin la autorización previa correspondiente. 
• Fumar, empujar, utilizar palabras groseras y demás actividades que alteren el orden de los escenarios deportivos.
 • Incurrir en cualquier tipo de comportamiento que ponga en riesgo la integridad y vida de los visitantes de las instalaciones, equipos e implementos deportivos. 
• Ingresar personas ajenas a las autorizadas para las actividades deportivas. 
• Utilizar anillos, cadenas u otro tipo de metal al iniciar las actividades deportivas.
•Consumir sustancias psicoactivas y alcohólicas.

A PARTIR DEL 15 DE MARZO DE 2022, TODO CLUB O PERSONA NATURAL QUE SE ESTE USUFRUCTUANDO DEL USO DE LOS ESCENARIOS DEPORTIVOS DEBERÁ CANCELAR EL VALOR DEL ALQUILER DEL MISMO, DE ACUERDO A LA INTENSIDAD HORARIA SOLICITADA, ACUERDO 004 DE 2022

ASI MISMO EL INDERBU NO SE HACE RESPONSABLE DE NINGÚN CASO DE VIOLENCIA   FISICA, LESIONES PERSONALES O MUERTE QUE SE PRESENTE EN LOS ESCENARIOS DEPORTIVOS A CAUSA DE RIÑAS OCACIONADAS POR PARTE DE LOS PETICIONARIOS.

EL INDERBU SE EXIME DE TODA RESPONSABILIDAD RELACIONADA A TODO ACCIDENTE INHERENTE AL EJERCICIO DE ACTIVIDADES RECREO DEPORTIVAS, YA QUE CADA QUIEN ASUME EL RIESGO DE PRACTICAR EL DEPORTE DE SU GUSTO.

EL INDERBU NO SE RESPONSABILIZA POR LOS DAÑOS A LOS BIENES MUEBLES DE LOS SOLICITANTES, EL INDERBU TIENE LA POTESTAD DE CANCELAR LA RESERVA SOLICITADA Y HACER USO DE ELLA EN CASO DE IMPREVISTOS INTERNOS DE LA ENTIDAD.

EL TITULAR DE LA RESERVA DEBE HACER PRESENCIA PARA EL INGRESO Y DURANTE EL TRANSCURSO DE TIEMPO DE LA RESERVA.

PARA EL INGRESO A LOS ESCENARIOS DEPORTIVOS ES OBLIGATORIO REGISTRARSE - LOS MENORES DE EDAD DEBEN ESTAR ACOMPAÑADOS POR AL MENOS UN (1) ADULTO RESPONSABLE 

NOTA: EL PRESENTE COMPROMISO SE ENTENDERA PERFECCIONADO UNA VEZ EL PETICIONARIO ACEPTE LAS CONDICIONES Y RESTRICCIONES AQUÍ PLAMADAS EL REQUERIMIENTO SERA AGENDADA Y LA SOLICITUD Y QUEDARA EN FIRME.`;
