import Footer from "@/features/home/components/organisms/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ScenarioLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    <Footer />
    </>
  )
}
